/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package medica;

import java.awt.CardLayout;
import javax.swing.ImageIcon;
import javax.swing.JFrame;


public class frmUtama extends javax.swing.JFrame {
private panAbout PANEL_ABOUT;
private panAdmin PANEL_ADMIN;
private panDokter PANEL_DOKTER;
private panHelp PANEL_HELP;
private panKamar PANEL_KAMAR;
private panPasienBayi PANEL_PASIENBAYI;
private panPasienBayiMati PANEL_PASIENBAYIMATI;
private panPasienIbu PANEL_PASIENIBU;
private panPasienIbuMati PANEL_PASIENIBUMATI;
private panPenyakit PENEL_PENYAKIT;
private panRawatInapBayi PANEL_RAWATINAPBAYI;
private panRawatInapIbu PANEL_RAWATINAPIBU;
private panRawatJalanBayi PANEL_RAWATJALANBAYI;
private panRawatJalanIbu PANEL_RAWATJALANIBU;
private panTindakan PANEL_TINDAKAN;
private panUtama PANEL_UTAMA;


    /**
     * Creates new form frmUtama
     */
    public frmUtama() {
        initComponents();
        icon();
        setLocationRelativeTo(null);
        setTitle(".::SISTEM INFORMASI MANAGEMEN RUMAH SAKIT::.");
        PANEL_ABOUT         = new panAbout();
        PANEL_ADMIN         = new panAdmin();
        PANEL_DOKTER        = new panDokter();
        PANEL_HELP          = new panHelp();
        PANEL_KAMAR         = new panKamar();
        PANEL_PASIENBAYI    = new panPasienBayi();
        PANEL_PASIENBAYIMATI= new panPasienBayiMati();
        PANEL_PASIENIBU     = new panPasienIbu();
        PANEL_PASIENIBUMATI = new panPasienIbuMati();
        PENEL_PENYAKIT      = new panPenyakit();
        PANEL_RAWATINAPBAYI = new panRawatInapBayi();
        PANEL_RAWATINAPIBU  = new panRawatInapIbu();
        PANEL_RAWATJALANBAYI= new panRawatJalanBayi();
        PANEL_RAWATJALANIBU = new panRawatJalanIbu();
        PANEL_TINDAKAN      = new panTindakan();
        PANEL_UTAMA         = new panUtama();
        panUtama.add("panAbout", PANEL_ABOUT);
        panUtama.add("panAdmin", PANEL_ADMIN);
        panUtama.add("panDokter",PANEL_DOKTER);
        panUtama.add("panHelp", PANEL_HELP);
        panUtama.add("panKamar",PANEL_KAMAR);
        panUtama.add("panPasienBayi", PANEL_PASIENBAYI);
        panUtama.add("panPasienBayiMati", PANEL_PASIENBAYIMATI);
        panUtama.add("panPasienIbu", PANEL_PASIENIBU);
        panUtama.add("panPasienIbuMati", PANEL_PASIENIBUMATI);
        panUtama.add("panPenyakit", PENEL_PENYAKIT);
        panUtama.add("panRawatInapBayi", PANEL_RAWATINAPBAYI);
        panUtama.add("panRawatInapIbu", PANEL_RAWATINAPIBU);
        panUtama.add("panRawatJalanBayi", PANEL_RAWATJALANBAYI);
        panUtama.add("panRawatJalanIbu", PANEL_RAWATJALANIBU);
        panUtama.add("panTindakan", PANEL_TINDAKAN);
        panUtama.add("panUtama", PANEL_UTAMA);
        showpanel("panUtama");
        
    }
    public void icon(){
        ImageIcon icon=new ImageIcon("src/images/about.png");
            setIconImage(icon.getImage());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgrond1 = new desain.Backgrond();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        fTransparan1 = new desain.FTransparan();
        buttonBig1 = new desain.ButtonBig();
        buttonBig2 = new desain.ButtonBig();
        buttonBig3 = new desain.ButtonBig();
        buttonBig20 = new desain.ButtonBig();
        buttonBig8 = new desain.ButtonBig();
        fTransparan2 = new desain.FTransparan();
        buttonBig4 = new desain.ButtonBig();
        buttonBig5 = new desain.ButtonBig();
        buttonBig6 = new desain.ButtonBig();
        buttonBig7 = new desain.ButtonBig();
        buttonBig17 = new desain.ButtonBig();
        fTransparan3 = new desain.FTransparan();
        buttonBig9 = new desain.ButtonBig();
        buttonBig10 = new desain.ButtonBig();
        buttonBig11 = new desain.ButtonBig();
        buttonBig12 = new desain.ButtonBig();
        fTransparan4 = new desain.FTransparan();
        buttonBig13 = new desain.ButtonBig();
        buttonBig14 = new desain.ButtonBig();
        buttonBig15 = new desain.ButtonBig();
        buttonBig16 = new desain.ButtonBig();
        panUtama = new desain.FTransparan();
        footer = new desain.FTransparan();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/aa.png"))); // NOI18N

        buttonBig1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/login.png"))); // NOI18N
        buttonBig1.setText("LogOut");
        buttonBig1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBig1ActionPerformed(evt);
            }
        });

        buttonBig2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/about.png"))); // NOI18N
        buttonBig2.setText("About");
        buttonBig2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBig2ActionPerformed(evt);
            }
        });

        buttonBig3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/help.png"))); // NOI18N
        buttonBig3.setText("Help");
        buttonBig3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBig3ActionPerformed(evt);
            }
        });

        buttonBig20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit.png"))); // NOI18N
        buttonBig20.setText("Exit");
        buttonBig20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBig20ActionPerformed(evt);
            }
        });

        buttonBig8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/house-icon.png"))); // NOI18N
        buttonBig8.setText("Home");
        buttonBig8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBig8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout fTransparan1Layout = new javax.swing.GroupLayout(fTransparan1);
        fTransparan1.setLayout(fTransparan1Layout);
        fTransparan1Layout.setHorizontalGroup(
            fTransparan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fTransparan1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buttonBig8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonBig1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonBig2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonBig3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonBig20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 645, Short.MAX_VALUE))
        );

        fTransparan1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {buttonBig1, buttonBig2, buttonBig20, buttonBig3, buttonBig8});

        fTransparan1Layout.setVerticalGroup(
            fTransparan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fTransparan1Layout.createSequentialGroup()
                .addGroup(fTransparan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonBig2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonBig3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonBig1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonBig8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonBig20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        fTransparan1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {buttonBig1, buttonBig2, buttonBig20, buttonBig3});

        jTabbedPane1.addTab("File", fTransparan1);

        buttonBig4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/guru.png"))); // NOI18N
        buttonBig4.setText("Kelola Dokter");
        buttonBig4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBig4ActionPerformed(evt);
            }
        });

        buttonBig5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/kelas.png"))); // NOI18N
        buttonBig5.setText("Kelola Kamar");
        buttonBig5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBig5ActionPerformed(evt);
            }
        });

        buttonBig6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/siswa.png"))); // NOI18N
        buttonBig6.setText("Kelola Penyakit");
        buttonBig6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBig6ActionPerformed(evt);
            }
        });

        buttonBig7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/chek.png"))); // NOI18N
        buttonBig7.setText("Kelola Tindakan");
        buttonBig7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBig7ActionPerformed(evt);
            }
        });

        buttonBig17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/seting.png"))); // NOI18N
        buttonBig17.setText("Kelola Admin");
        buttonBig17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBig17ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout fTransparan2Layout = new javax.swing.GroupLayout(fTransparan2);
        fTransparan2.setLayout(fTransparan2Layout);
        fTransparan2Layout.setHorizontalGroup(
            fTransparan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fTransparan2Layout.createSequentialGroup()
                .addComponent(buttonBig4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonBig5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonBig7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonBig6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonBig17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 493, Short.MAX_VALUE))
        );

        fTransparan2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {buttonBig4, buttonBig5, buttonBig6, buttonBig7});

        fTransparan2Layout.setVerticalGroup(
            fTransparan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fTransparan2Layout.createSequentialGroup()
                .addGroup(fTransparan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonBig4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonBig5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonBig6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonBig7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(buttonBig17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        fTransparan2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {buttonBig4, buttonBig5, buttonBig6, buttonBig7});

        jTabbedPane1.addTab("Kelola Master", fTransparan2);

        buttonBig9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/guru.png"))); // NOI18N
        buttonBig9.setText("Ibu");
        buttonBig9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBig9ActionPerformed(evt);
            }
        });

        buttonBig10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/guru.png"))); // NOI18N
        buttonBig10.setText("Ibu Mati");
        buttonBig10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBig10ActionPerformed(evt);
            }
        });

        buttonBig11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user.png"))); // NOI18N
        buttonBig11.setText("Bayi");
        buttonBig11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBig11ActionPerformed(evt);
            }
        });

        buttonBig12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user.png"))); // NOI18N
        buttonBig12.setText("Bayi Mati");
        buttonBig12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBig12ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout fTransparan3Layout = new javax.swing.GroupLayout(fTransparan3);
        fTransparan3.setLayout(fTransparan3Layout);
        fTransparan3Layout.setHorizontalGroup(
            fTransparan3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fTransparan3Layout.createSequentialGroup()
                .addComponent(buttonBig9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonBig10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonBig11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonBig12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 756, Short.MAX_VALUE))
        );

        fTransparan3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {buttonBig10, buttonBig11, buttonBig12, buttonBig9});

        fTransparan3Layout.setVerticalGroup(
            fTransparan3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fTransparan3Layout.createSequentialGroup()
                .addGroup(fTransparan3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonBig10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonBig11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonBig12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonBig9, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        fTransparan3Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {buttonBig10, buttonBig11, buttonBig12, buttonBig9});

        jTabbedPane1.addTab("Pasien", fTransparan3);

        buttonBig13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/guru.png"))); // NOI18N
        buttonBig13.setText("Jalan Ibu");
        buttonBig13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBig13ActionPerformed(evt);
            }
        });

        buttonBig14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/guru.png"))); // NOI18N
        buttonBig14.setText("Inap Ibu");
        buttonBig14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBig14ActionPerformed(evt);
            }
        });

        buttonBig15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user.png"))); // NOI18N
        buttonBig15.setText("Jalan Bayi");
        buttonBig15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBig15ActionPerformed(evt);
            }
        });

        buttonBig16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user.png"))); // NOI18N
        buttonBig16.setText("Inap Bayi");
        buttonBig16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBig16ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout fTransparan4Layout = new javax.swing.GroupLayout(fTransparan4);
        fTransparan4.setLayout(fTransparan4Layout);
        fTransparan4Layout.setHorizontalGroup(
            fTransparan4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fTransparan4Layout.createSequentialGroup()
                .addComponent(buttonBig13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonBig14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonBig15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonBig16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 736, Short.MAX_VALUE))
        );

        fTransparan4Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {buttonBig13, buttonBig14, buttonBig15, buttonBig16});

        fTransparan4Layout.setVerticalGroup(
            fTransparan4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fTransparan4Layout.createSequentialGroup()
                .addGroup(fTransparan4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonBig14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonBig15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonBig16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonBig13, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        fTransparan4Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {buttonBig13, buttonBig14, buttonBig15, buttonBig16});

        jTabbedPane1.addTab("Rawat", fTransparan4);

        panUtama.setBackground(new java.awt.Color(204, 255, 0));
        panUtama.setLayout(new java.awt.CardLayout());

        footer.setBackground(new java.awt.Color(255, 102, 0));

        jLabel2.setText("Copyright Design By arie wah");

        javax.swing.GroupLayout footerLayout = new javax.swing.GroupLayout(footer);
        footer.setLayout(footerLayout);
        footerLayout.setHorizontalGroup(
            footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, footerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(468, 468, 468))
        );
        footerLayout.setVerticalGroup(
            footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(footerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout backgrond1Layout = new javax.swing.GroupLayout(backgrond1);
        backgrond1.setLayout(backgrond1Layout);
        backgrond1Layout.setHorizontalGroup(
            backgrond1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panUtama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(footer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(backgrond1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(backgrond1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1095, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        backgrond1Layout.setVerticalGroup(
            backgrond1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgrond1Layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panUtama, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(footer, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(backgrond1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(backgrond1Layout.createSequentialGroup()
                    .addGap(74, 74, 74)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(75, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgrond1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgrond1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonBig3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBig3ActionPerformed
        panUtama.setVisible(true);
        showpanel("panHelp");
    }//GEN-LAST:event_buttonBig3ActionPerformed

    private void buttonBig20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBig20ActionPerformed
        dispose();
    }//GEN-LAST:event_buttonBig20ActionPerformed

    private void buttonBig9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBig9ActionPerformed
        panUtama.setVisible(true);
        showpanel("panPasienIbu");
    }//GEN-LAST:event_buttonBig9ActionPerformed

    private void buttonBig1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBig1ActionPerformed
        this.dispose();
        Login login=new Login();
        login.setVisible(true);
    }//GEN-LAST:event_buttonBig1ActionPerformed

    private void buttonBig2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBig2ActionPerformed
        panUtama.setVisible(true);
        showpanel("panAbout");
    }//GEN-LAST:event_buttonBig2ActionPerformed

    private void buttonBig4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBig4ActionPerformed
        panUtama.setVisible(true);
        showpanel("panDokter");
        
    }//GEN-LAST:event_buttonBig4ActionPerformed

    private void buttonBig5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBig5ActionPerformed
        panUtama.setVisible(true);
        showpanel("panKamar");
    }//GEN-LAST:event_buttonBig5ActionPerformed

    private void buttonBig7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBig7ActionPerformed
        panUtama.setVisible(true);
        showpanel("panTindakan");
    }//GEN-LAST:event_buttonBig7ActionPerformed

    private void buttonBig6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBig6ActionPerformed
        panUtama.setVisible(true);
        showpanel("panPenyakit");
    }//GEN-LAST:event_buttonBig6ActionPerformed

    private void buttonBig17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBig17ActionPerformed
        panUtama.setVisible(true);
        showpanel("panAdmin");
    }//GEN-LAST:event_buttonBig17ActionPerformed

    private void buttonBig10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBig10ActionPerformed
        panUtama.setVisible(true);
        showpanel("panPasienIbuMati");
    }//GEN-LAST:event_buttonBig10ActionPerformed

    private void buttonBig11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBig11ActionPerformed
        panUtama.setVisible(true);
        showpanel("panPasienBayi");
    }//GEN-LAST:event_buttonBig11ActionPerformed

    private void buttonBig12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBig12ActionPerformed
        panUtama.setVisible(true);
        showpanel("panPasienBayiMati");
    }//GEN-LAST:event_buttonBig12ActionPerformed

    private void buttonBig13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBig13ActionPerformed
        panUtama.setVisible(true);
        showpanel("panRawatJalanIbu");
    }//GEN-LAST:event_buttonBig13ActionPerformed

    private void buttonBig14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBig14ActionPerformed
        panUtama.setVisible(true);
        showpanel("panRawatInapIbu");
    }//GEN-LAST:event_buttonBig14ActionPerformed

    private void buttonBig15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBig15ActionPerformed
        panUtama.setVisible(true);
        showpanel("panRawatJalanBayi");
    }//GEN-LAST:event_buttonBig15ActionPerformed

    private void buttonBig16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBig16ActionPerformed
        panUtama.setVisible(true);
        showpanel("panRawatInapBayi");
    }//GEN-LAST:event_buttonBig16ActionPerformed

    private void buttonBig8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBig8ActionPerformed
        panUtama.setVisible(true);
        showpanel("panUtama");
    }//GEN-LAST:event_buttonBig8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmUtama().setVisible(true);
                //frmUtama mn=new frmUtama();
                //mn.setExtendedState(JFrame.MAXIMIZED_BOTH);
                //mn.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private desain.Backgrond backgrond1;
    private desain.ButtonBig buttonBig1;
    private desain.ButtonBig buttonBig10;
    private desain.ButtonBig buttonBig11;
    private desain.ButtonBig buttonBig12;
    private desain.ButtonBig buttonBig13;
    private desain.ButtonBig buttonBig14;
    private desain.ButtonBig buttonBig15;
    private desain.ButtonBig buttonBig16;
    private desain.ButtonBig buttonBig17;
    private desain.ButtonBig buttonBig2;
    private desain.ButtonBig buttonBig20;
    private desain.ButtonBig buttonBig3;
    private desain.ButtonBig buttonBig4;
    private desain.ButtonBig buttonBig5;
    private desain.ButtonBig buttonBig6;
    private desain.ButtonBig buttonBig7;
    private desain.ButtonBig buttonBig8;
    private desain.ButtonBig buttonBig9;
    private desain.FTransparan fTransparan1;
    private desain.FTransparan fTransparan2;
    private desain.FTransparan fTransparan3;
    private desain.FTransparan fTransparan4;
    private desain.FTransparan footer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private desain.FTransparan panUtama;
    // End of variables declaration//GEN-END:variables

    private void showpanel(String panelIdentifier) {
        CardLayout cardLayout=(CardLayout) panUtama.getLayout();
        cardLayout.show(panUtama, panelIdentifier);
    }
}
